# Generated by Django 6.0.6 on 2026-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_company_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
